FXPS7xxx_Arduino: FXPS7xxx_Arduino Class Reference
FXPS7xxx_Arduino Class Reference
Class to evaluate FXPS7xxxD4.
#include <FXPS7xxx_Arduino.h>
Public Types
enum class communicationInterface { _SPI , _I2C , _ANA }
enum class pressureRange { P115 =0 , P250 =1 }
enum class command_SPI { _SPI_R = 0xC0 , _SPI_W = 0x80 }
Public Member Functions
uint8_t init ()
Initialization function: Execute once after definition.
void reset ()
Reset function: To send 00->11->01 to DEVLOCK_WR[RESET].
uint8_t read_reg (uint8_t address, uint8_t num, uint8_t *pReadBuffer)
Register read function: Interface is selected automatically.
uint8_t read_reg_i2c (uint8_t address, uint8_t num, uint8_t *pReadBuffer)
Register read function for I2C: Called by read_reg() function.
uint8_t read_reg_spi (uint8_t address, uint8_t num, uint8_t *pReadBuffer)
Register read function for SPI: Called by read_reg() function.
uint8_t write_reg (uint8_t address, uint8_t writeBuffer)
Register write function: Interface is selected automatically.
uint8_t write_reg_i2c (uint8_t address, uint8_t writeBuffer)
Register write function for I2C: Called by write_reg() function, calls access_reg_spi()
uint8_t write_reg_spi (uint8_t address, uint8_t writeBuffer)
Register write function for SPI: Called by write_reg() function, calls access_reg_spi()
uint8_t access_reg_spi (uint8_t *p_spi_txdata)
Register access function: SPI command is complex, so this function wraps SPI communication.
float get_pressure_sensor_data_request (uint8_t sourceid)
Sensor data request command: SPI Only, takes 16-bit or 12-bit sensor data.
float get_pressure (uint8_t sensor)
Function to read pressure data by register: Takes 16-bit sensor data by reading SNSDATAx_y.
int16_t get_temperature ()
Function to read pressure data by register: Takes temperature data by reading TEMPERATURE.
uint8_t self_test (uint8_t mode)
Function to activate self-test.
uint8_t u8Crc_Calculate (uint8_t *p_u8_cmd_msg)
Function to calculate CRC8, normally only used in SPI.
FXPS7xxx_Arduino (communicationInterface _comType, pressureRange _P_range)
Constructor for FXPS7xxx_Arduino: Device type is selected from definition.
FXPS7xxx_Arduino (communicationInterface _comType, pressureRange _P_range, uint8_t _debug)
Constructor for FXPS7xxx_Arduino with debug mode: Device type is selected from definition.
Public Attributes
uint8_t debug =0
Debug mode (1 to indicate sent/received hex data in serial)
communicationInterface comType
Variable to indicate communication interface.
pressureRange P_range
Variable to indicate pressure range.
uint8_t sourceid0
uint8_t sourceid1
uint8_t num_sensor_data =0
SPI Only: Source ID and which sensor to obtain data from.
SPISettings spi_settings = SPISettings(100000, MSBFIRST, SPI_MODE0)
SPI Only: Settings to use in SPI mode.
uint8_t spi_ss = SS
SPI Only: /CS pin to use.
uint8_t spi_txdata [4]
SPI Only: TX data.
uint8_t spi_rxdata [4]
SPI Only: RX data.
uint8_t I2C_address = 0x60
Variable to indicate I2C address, default to be 0x60.
const uint16_t fixed_st [4] = {0x0, 0xAAAA, 0x5555, 0xFFFF}
Self-Test for fixed.
const uint16_t digital_st [4] = {0x8171, 0x6C95, 0x807A, 0x78AC}
Self-Test for digital.
const float PABSOFF_12sdr [2] = {-1567.8, -4.2}
Offset coefficient to be used at 12-bit Sensor data request command.
const float PABS_sense_12sdr [2] = {46.67, 15.21}
Sensitivity coefficient to be used at 12-bit Sensor data request command.
const float PABSOFF_16reg [2] = {25536, 28661.6}
Offset coefficient to be used at Register read command.
const float PABS_sense_16reg [2] = {93.34, 30.42}
Sensitivity coefficient to be used at Register read command.
const float PABSOFF_16sdr [2] = {-25084.8, 67.41}
Offset coefficient to be used at 16-bit Sensor data request command.
const float PABS_sense_16sdr [2] = {746.72, 243.36}
Sensitivity coefficient to be used at 16-bit Sensor data request command.
Detailed Description
Class to evaluate FXPS7xxxD4.
Definition at line 40 of file FXPS7xxx_Arduino.h.
Member Enumeration Documentation
command_SPI
enum class FXPS7xxx_Arduino::command_SPI strong
Definition at line 45 of file FXPS7xxx_Arduino.h.
communicationInterface
enum class FXPS7xxx_Arduino::communicationInterface strong
Definition at line 43 of file FXPS7xxx_Arduino.h.
pressureRange
enum class FXPS7xxx_Arduino::pressureRange strong
Definition at line 44 of file FXPS7xxx_Arduino.h.
Constructor & Destructor Documentation
FXPS7xxx_Arduino() [1/2]
FXPS7xxx_Arduino::FXPS7xxx_Arduino (communicationInterface _comType, pressureRange _P_range) inline
Constructor for FXPS7xxx_Arduino: Device type is selected from definition.
Parameters
Communication interface type: Selected from FXPS7XXX_I2C, FXPS7XXX_SPI, or FXPS7XXX_ANA
Pressure range: Selected from P_RANGE
Definition at line 179 of file FXPS7xxx_Arduino.h.
FXPS7xxx_Arduino() [2/2]
FXPS7xxx_Arduino::FXPS7xxx_Arduino (communicationInterface _comType, pressureRange _P_range, uint8_t _debug) inline
Constructor for FXPS7xxx_Arduino with debug mode: Device type is selected from definition.
Parameters
Communication interface type: Selected from FXPS7XXX_I2C, FXPS7XXX_SPI, or FXPS7XXX_ANA
Pressure range: Selected from P_RANGE
debug mode (1 to show raw communication data in serial, Only available at SPI)
Definition at line 190 of file FXPS7xxx_Arduino.h.
Member Function Documentation
access_reg_spi()
uint8_t FXPS7xxx_Arduino::access_reg_spi (uint8_t * p_spi_txdata)
Register access function: SPI command is complex, so this function wraps SPI communication.
Parameters
Pointer to contents to be sent
Returns
Status (sensor_error_type)
Definition at line 172 of file FXPS7xxx_Arduino.cpp.
Referenced by get_pressure_sensor_data_request(), read_reg_spi(), and write_reg_spi().
get_pressure()
float FXPS7xxx_Arduino::get_pressure (uint8_t sensor)
Function to read pressure data by register: Takes 16-bit sensor data by reading SNSDATAx_y.
Parameters
Sensor number: Which sensor to access, 0 or 1
Returns
Pressure data (float)
Definition at line 198 of file FXPS7xxx_Arduino.cpp.
get_pressure_sensor_data_request()
float FXPS7xxx_Arduino::get_pressure_sensor_data_request (uint8_t sourceid)
Sensor data request command: SPI Only, takes 16-bit or 12-bit sensor data.
Parameters
Sensor number: Which sensor to access, 0 or 1
Returns
Pressure data (float)
Definition at line 142 of file FXPS7xxx_Arduino.cpp.
get_temperature()
int16_t FXPS7xxx_Arduino::get_temperature ()
Function to read pressure data by register: Takes temperature data by reading TEMPERATURE.
Parameters
Sensor number: Which sensor to access, 0 or 1
Returns
Temperature data in unit of degC (Signed int16)
Definition at line 212 of file FXPS7xxx_Arduino.cpp.
init()
uint8_t FXPS7xxx_Arduino::init ()
Initialization function: Execute once after definition.
Definition at line 18 of file FXPS7xxx_Arduino.cpp.
read_reg()
uint8_t FXPS7xxx_Arduino::read_reg (uint8_t address, uint8_t num, uint8_t * pReadBuffer)
Register read function: Interface is selected automatically.
Parameters
Register address to access
Number of register to be read
Pointer to array to store register contents
Returns
Status (sensor_error_type)
Definition at line 56 of file FXPS7xxx_Arduino.cpp.
Referenced by get_pressure(), get_temperature(), init(), and self_test().
read_reg_i2c()
uint8_t FXPS7xxx_Arduino::read_reg_i2c (uint8_t address, uint8_t num, uint8_t * pReadBuffer)
Register read function for I2C: Called by read_reg() function.
Parameters
Register address to access
Number of register to be read
Pointer to array to store register contents
Returns
Status (sensor_error_type)
Definition at line 84 of file FXPS7xxx_Arduino.cpp.
Referenced by read_reg().
read_reg_spi()
uint8_t FXPS7xxx_Arduino::read_reg_spi (uint8_t address, uint8_t num, uint8_t * pReadBuffer)
Register read function for SPI: Called by read_reg() function.
Parameters
Register address to access
Number of register to be read
Pointer to array to store register contents
Returns
Status (sensor_error_type)
Definition at line 115 of file FXPS7xxx_Arduino.cpp.
Referenced by read_reg().
reset()
void FXPS7xxx_Arduino::reset ()
Reset function: To send 00->11->01 to DEVLOCK_WR[RESET].
Definition at line 48 of file FXPS7xxx_Arduino.cpp.
Referenced by init().
self_test()
uint8_t FXPS7xxx_Arduino::self_test (uint8_t mode)
Function to activate self-test.
Parameters
Self-Test Mode
Returns
Status (sensor_error_type)
Definition at line 218 of file FXPS7xxx_Arduino.cpp.
u8Crc_Calculate()
uint8_t FXPS7xxx_Arduino::u8Crc_Calculate (uint8_t * p_u8_cmd_msg)
Function to calculate CRC8, normally only used in SPI.
Parameters
Pointer to calculate CRC
Returns
CRC result
Definition at line 254 of file FXPS7xxx_Arduino.cpp.
Referenced by access_reg_spi().
write_reg()
uint8_t FXPS7xxx_Arduino::write_reg (uint8_t address, uint8_t writeBuffer)
Register write function: Interface is selected automatically.
Parameters
Register address to access
Content to be written
Returns
Status (sensor_error_type)
Definition at line 70 of file FXPS7xxx_Arduino.cpp.
Referenced by read_reg_i2c(), read_reg_spi(), reset(), and self_test().
write_reg_i2c()
uint8_t FXPS7xxx_Arduino::write_reg_i2c (uint8_t address, uint8_t writeBuffer)
Register write function for I2C: Called by write_reg() function, calls access_reg_spi()
Parameters
Register address to access
Content to be written
Returns
Status (sensor_error_type)
Definition at line 107 of file FXPS7xxx_Arduino.cpp.
Referenced by write_reg().
write_reg_spi()
uint8_t FXPS7xxx_Arduino::write_reg_spi (uint8_t address, uint8_t writeBuffer)
Register write function for SPI: Called by write_reg() function, calls access_reg_spi()
Parameters
Register address to access
Content to be written
Returns
Status (sensor_error_type)
Definition at line 161 of file FXPS7xxx_Arduino.cpp.
Referenced by write_reg().
Member Data Documentation
comType
communicationInterface FXPS7xxx_Arduino::comType
Variable to indicate communication interface.
Definition at line 47 of file FXPS7xxx_Arduino.h.
Referenced by FXPS7xxx_Arduino(), FXPS7xxx_Arduino(), get_pressure(), get_pressure_sensor_data_request(), init(), read_reg(), reset(), and write_reg().
debug
uint8_t FXPS7xxx_Arduino::debug =0
Debug mode (1 to indicate sent/received hex data in serial)
Definition at line 42 of file FXPS7xxx_Arduino.h.
Referenced by access_reg_spi(), and FXPS7xxx_Arduino().
digital_st
const uint16_t FXPS7xxx_Arduino::digital_st[4] = {0x8171, 0x6C95, 0x807A, 0x78AC}
Self-Test for digital.
Definition at line 59 of file FXPS7xxx_Arduino.h.
Referenced by self_test().
fixed_st
const uint16_t FXPS7xxx_Arduino::fixed_st[4] = {0x0, 0xAAAA, 0x5555, 0xFFFF}
Self-Test for fixed.
Definition at line 58 of file FXPS7xxx_Arduino.h.
Referenced by self_test().
I2C_address
uint8_t FXPS7xxx_Arduino::I2C_address = 0x60
Variable to indicate I2C address, default to be 0x60.
Definition at line 56 of file FXPS7xxx_Arduino.h.
Referenced by read_reg_i2c(), and write_reg_i2c().
num_sensor_data
uint8_t FXPS7xxx_Arduino::num_sensor_data =0
SPI Only: Source ID and which sensor to obtain data from.
Definition at line 50 of file FXPS7xxx_Arduino.h.
Referenced by get_pressure_sensor_data_request(), and write_reg_spi().
P_range
pressureRange FXPS7xxx_Arduino::P_range
Variable to indicate pressure range.
Definition at line 48 of file FXPS7xxx_Arduino.h.
Referenced by FXPS7xxx_Arduino(), and FXPS7xxx_Arduino().
PABS_sense_12sdr
const float FXPS7xxx_Arduino::PABS_sense_12sdr[2] = {46.67, 15.21}
Sensitivity coefficient to be used at 12-bit Sensor data request command.
Definition at line 62 of file FXPS7xxx_Arduino.h.
Referenced by get_pressure_sensor_data_request().
PABS_sense_16reg
const float FXPS7xxx_Arduino::PABS_sense_16reg[2] = {93.34, 30.42}
Sensitivity coefficient to be used at Register read command.
Definition at line 64 of file FXPS7xxx_Arduino.h.
Referenced by get_pressure().
PABS_sense_16sdr
const float FXPS7xxx_Arduino::PABS_sense_16sdr[2] = {746.72, 243.36}
Sensitivity coefficient to be used at 16-bit Sensor data request command.
Definition at line 66 of file FXPS7xxx_Arduino.h.
Referenced by get_pressure_sensor_data_request().
PABSOFF_12sdr
const float FXPS7xxx_Arduino::PABSOFF_12sdr[2] = {-1567.8, -4.2}
Offset coefficient to be used at 12-bit Sensor data request command.
Definition at line 61 of file FXPS7xxx_Arduino.h.
Referenced by get_pressure_sensor_data_request().
PABSOFF_16reg
const float FXPS7xxx_Arduino::PABSOFF_16reg[2] = {25536, 28661.6}
Offset coefficient to be used at Register read command.
Definition at line 63 of file FXPS7xxx_Arduino.h.
Referenced by get_pressure().
PABSOFF_16sdr
const float FXPS7xxx_Arduino::PABSOFF_16sdr[2] = {-25084.8, 67.41}
Offset coefficient to be used at 16-bit Sensor data request command.
Definition at line 65 of file FXPS7xxx_Arduino.h.
Referenced by get_pressure_sensor_data_request().
sourceid0
uint8_t FXPS7xxx_Arduino::sourceid0
Definition at line 50 of file FXPS7xxx_Arduino.h.
sourceid1
uint8_t FXPS7xxx_Arduino::sourceid1
Definition at line 50 of file FXPS7xxx_Arduino.h.
spi_rxdata
uint8_t FXPS7xxx_Arduino::spi_rxdata[4]
SPI Only: RX data.
Definition at line 54 of file FXPS7xxx_Arduino.h.
Referenced by access_reg_spi(), get_pressure_sensor_data_request(), and read_reg_spi().
spi_settings
SPISettings FXPS7xxx_Arduino::spi_settings = SPISettings(100000, MSBFIRST, SPI_MODE0)
SPI Only: Settings to use in SPI mode.
Definition at line 51 of file FXPS7xxx_Arduino.h.
Referenced by access_reg_spi().
spi_ss
uint8_t FXPS7xxx_Arduino::spi_ss = SS
SPI Only: /CS pin to use.
Definition at line 52 of file FXPS7xxx_Arduino.h.
Referenced by access_reg_spi().
spi_txdata
uint8_t FXPS7xxx_Arduino::spi_txdata[4]
SPI Only: TX data.
Definition at line 53 of file FXPS7xxx_Arduino.h.
Referenced by access_reg_spi().
The documentation for this class was generated from the following files:
FXPS7xxx_Arduino.h
FXPS7xxx_Arduino.cpp